target-version = "py310"
line-length = 100

exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "dist",
    ".secrets",
    ".vscode",
    "tests"
]

[lint]
extend-select = ["C901"]
ignore = ["E722", "E712"]
[lint.mccabe]
max-complexity = 35